import asyncio
from typing import Any, AsyncGenerator
from collections.abc import AsyncIterable
from agent_framework import CheckpointStorage, Content,AgentResponseUpdate, Agent,InMemoryCheckpointStorage,WorkflowCheckpoint, WorkflowEvent
from agent_framework.exceptions import AgentFrameworkException
from agent_framework.orchestrations import HandoffBuilder,HandoffAgentUserRequest
from agent_framework.openai import OpenAIChatCompletionClient
from app.agents.azure_chat.account_agent import AccountAgent
from app.agents.azure_chat.transaction_agent import TransactionHistoryAgent
from app.agents.azure_chat.payment_agent import PaymentAgent
from app.agents.azure_chat.customer_agent import CustomerAgent
from app.agents.azure_chat.loan_agent import LoanAgent
from app.agents.azure_chat.credit_agent import CreditAgent
from app.agents.azure_chat.document_agent import DocumentAgent
from app.agents.azure_chat.communication_agent import CommunicationAgent
from app.agents.azure_chat.investment_agent import InvestmentAgent
from app.helpers.no_history_provider import NoHistoryProvider
from app.helpers.conversation_logger import TurnTracker
from uuid import uuid4
import logging

logger = logging.getLogger(__name__)

class HandoffOrchestrator:
    
    triage_instructions = """
      You are a banking customer support agent triaging customer requests about their banking account, movements, payments,
      customer profile, loans, credit, documents, and communications.
      You have to evaluate the whole conversation with the customer and handoff to the right specialist agent.
      When delegation is required, call the matching handoff tool based on triage rules.


      # Triage rules
      - If the user request is related to bank account information like account balance, payment methods, cards and beneficiaries book you must call handoff_to_AccountAgent.
      - If the user request is related to banking movements and payments history, you must call handoff_to_TransactionHistoryAgent.
      - If the user request is related to initiate a payment request, upload a bill or invoice image for payment or manage an on-going payment process, you must call handoff_to_PaymentAgent.
      - If the user request is related to their customer profile, contact details, or (for admins) searching for other customers, you must call handoff_to_CustomerAgent.
      - If the user request is related to loan applications, loan status, EMI schedules, or (for admins) approving/rejecting loans, you must call handoff_to_LoanAgent.
      - If the user request is related to credit score or credit history, you must call handoff_to_CreditAgent.
      - If the user request is related to generating or retrieving a statement, receipt, or loan letter, you must call handoff_to_DocumentAgent.
      - If the user request is related to sending an email/WhatsApp/notification or viewing communication history, you must call handoff_to_CommunicationAgent.
      - If the user request is related to their stock investment portfolio, holdings, stock prices, or buying/selling stocks, you must call handoff_to_InvestmentAgent.
      - If the user request is not related to any of the above you must respond to the user that you are not able to help with the request.


    """

    """ A simple in-memory store [workflow_id/thread_id, WorkflowCheckpoint] to keep track of threads per user/session.
     Thread_id and workflow_id are synonymous in this context. We are keeping the thread_id concept and assign it the workflow_id value generated by the agent framework.
    In production, this should be replaced with a persistent store like a database or distributed cache.
    """
    thread_checkpoint_store: dict[str, CheckpointStorage] = {}

    # HandoffOrchestrator is created fresh per HTTP request (DI Factory), so
    # without this cache, initialize() below rebuilt all 9 specialist agents
    # and reconnected every one of their MCP servers on EVERY single message.
    # Caching per-thread (not globally) keeps this safe: each thread's
    # workflow is only ever run sequentially within that thread, and it's
    # already paired 1:1 with that thread's own CheckpointStorage.
    thread_workflow_store: dict[str, Any] = {}

    # PERF-2026-08-19: thread_workflow_store above still means every brand-new
    # conversation pays the full agent-build cost once. That cost is entirely
    # MCP server connects for the 9 specialists + triage - none of it is
    # per-user state (identity is injected per-call via context providers,
    # never baked into the Agent object at build time), so it's safe to build
    # ONCE for the life of the process and share across every thread/user,
    # rather than once per thread. Only the Workflow graph itself (routing,
    # checkpoint wiring) needs to stay per-thread, since the framework refuses
    # to run one Workflow object concurrently - building that graph from
    # already-built agents is pure in-memory wiring, no I/O, effectively free.
    # Verified live on the foundry_v2 tree: two brand-new, concurrent
    # conversations sharing these objects both completed correctly with
    # distinct, properly-isolated answers.
    _participants: Any = None
    _participants_lock: asyncio.Lock = asyncio.Lock()

    def __init__(self,
                 azure_chat_client: OpenAIChatCompletionClient,
                 account_agent: AccountAgent,
                 transaction_agent: TransactionHistoryAgent,
                 payment_agent: PaymentAgent,
                 customer_agent: CustomerAgent,
                 loan_agent: LoanAgent,
                 credit_agent: CreditAgent,
                 document_agent: DocumentAgent,
                 communication_agent: CommunicationAgent,
                 investment_agent: InvestmentAgent
                                ):
      self.azure_chat_client = azure_chat_client
      self.account_agent = account_agent
      self.transaction_agent = transaction_agent
      self.payment_agent = payment_agent
      self.customer_agent = customer_agent
      self.loan_agent = loan_agent
      self.credit_agent = credit_agent
      self.document_agent = document_agent
      self.communication_agent = communication_agent
      self.investment_agent = investment_agent
      self.workflow = None  # Will be initialized in async method

    async def _get_or_build_participants(self) -> tuple[Any, list[Any]]:
      """Builds triage_agent + all 9 specialists (and connects all their MCP
      servers) once for the life of the process, then reuses that same set for
      every thread/user from then on. See _participants comment above for why
      this is safe. Guarded by a lock so concurrent first-requests build one
      shared set instead of racing to build duplicates.
      """
      if HandoffOrchestrator._participants is not None:
          return HandoffOrchestrator._participants

      async with HandoffOrchestrator._participants_lock:
          if HandoffOrchestrator._participants is not None:
              return HandoffOrchestrator._participants

          triage_agent = Agent(
                client=self.azure_chat_client,
                instructions=HandoffOrchestrator.triage_instructions,
                name="triage_agent",
                # NoHistoryProvider prevents the framework from auto-injecting an
                # InMemoryHistoryProvider.  Inside a HandoffBuilder workflow the
                # executor already tracks the full conversation, so the auto-injected
                # provider would duplicate messages on every turn, eventually causing
                # OpenAI 400 errors due to mismatched tool_calls / tool results.
                context_providers=[NoHistoryProvider()]
            )

          specialists = [
              await self.account_agent.build_af_agent(),
              await self.transaction_agent.build_af_agent(),
              await self.payment_agent.build_af_agent(),
              await self.customer_agent.build_af_agent(),
              await self.loan_agent.build_af_agent(),
              await self.credit_agent.build_af_agent(),
              await self.document_agent.build_af_agent(),
              await self.communication_agent.build_af_agent(),
              await self.investment_agent.build_af_agent(),
          ]

          HandoffOrchestrator._participants = (triage_agent, specialists)
          return HandoffOrchestrator._participants

    async def initialize(self, checkpoint_storage: CheckpointStorage, thread_id: str):
      """Build the workflow graph for this thread from the shared, already-built
      agents (see _get_or_build_participants) and cache it (see
      thread_workflow_store). Each thread gets its own Workflow object - the
      framework refuses to run one Workflow instance concurrently - but building
      the graph itself is pure in-memory wiring around already-built agents, no
      I/O, so doing this per-thread costs virtually nothing.
      """
      triage_agent, specialists = await self._get_or_build_participants()

      self.workflow = (
        HandoffBuilder(
            name="banking_assistant_handoff",
            participants=[triage_agent, *specialists],
            termination_condition=lambda conv: sum(1 for msg in conv if msg.role == "user") >= 20,
            checkpoint_storage=checkpoint_storage,
        )
        .with_start_agent(triage_agent)
        .build()
    )
      HandoffOrchestrator.thread_workflow_store[thread_id] = self.workflow

            
    async def _get_or_create_checkpoint_store(self,thread_id: str) -> CheckpointStorage :
        checkpoint_storage = HandoffOrchestrator.thread_checkpoint_store.get(thread_id, None)
        if checkpoint_storage is not None:
            return checkpoint_storage

        logger.info(f"Creating new checkpoint storage for thread_id: {thread_id}")
        checkpoint_storage = InMemoryCheckpointStorage()
        HandoffOrchestrator.thread_checkpoint_store[thread_id] = checkpoint_storage
        return checkpoint_storage

    def reset_thread(self, thread_id: str) -> None:
        """Drop this thread's cached checkpoint + workflow so the next message
        starts a fresh conversation for it.

        Mitigation for a framework-level gap (agent_framework_orchestrations'
        HandoffAgentExecutor) where the tool_call/tool_result pairing recorded
        across an approval-gated resume can go stale, causing every later
        message in that thread to fail with an OpenAI 400 ("assistant message
        with tool_calls must be followed by tool messages"). Not a real fix -
        that lives in a vendored third-party package - but it turns a
        permanently broken thread into a one-time loss of that thread's
        context instead of a hard crash on every subsequent message.
        """
        HandoffOrchestrator.thread_checkpoint_store.pop(thread_id, None)
        HandoffOrchestrator.thread_workflow_store.pop(thread_id, None)

    
    async def _resume_workflow_with_response(self, checkpoint_storage: CheckpointStorage, checkpoint_id: str, user_message: str) -> AsyncIterable[WorkflowEvent]:
        """Resume a workflow from a checkpoint with a response to a RequestInfoEvent.

        Args:
            checkpoint (WorkflowCheckpoint): The checkpoint to resume from.
            response (dict[str, str]): The response mapping request IDs to user inputs.

        Yields:
            AsyncIterable[WorkflowEvent]: The events generated by resuming the workflow.
        """
        events = self.workflow.run(checkpoint_id=checkpoint_id,    #type: ignore
                                    checkpoint_storage=checkpoint_storage, 
                                    stream=True) 
        
        responses: dict[str, object] = {}
        
        #We need to collect all workflow events otherwise we get concurrent workflow execution error when trying to resume.
        consumed_events = [event async for event in events]
        for event in consumed_events:
            if event.type == "request_info":
                if isinstance(event.data, HandoffAgentUserRequest):
                        responses[event.request_id] = HandoffAgentUserRequest.create_response(user_message)
                        return self.workflow.run(responses=responses, checkpoint_id=checkpoint_id, #type: ignore
                                                 checkpoint_storage=checkpoint_storage, 
                                                 stream=True) 
                else:
                    raise AgentFrameworkException(f"RequestInfoEvent [{event.request_id}] found in the checkpoint [{checkpoint_id}] that is not a HandoffAgentUserRequest.")
        #if we reach here, something went wrong. For this use case HandoffOrchestrator expected to always trigger a RequestInfoEvent.
        raise AgentFrameworkException(f"No RequestInfoEvent found in the checkpoint [{checkpoint_id}]")
            
    
    async def processMessageStream(self, user_message: str , thread_id : str ) -> AsyncGenerator[WorkflowEvent,None]:

        tracker = TurnTracker(thread_id, "message", user_message)
        checkpoint_storage = await self._get_or_create_checkpoint_store(thread_id)
        tracker.mark_checkpoint_ready()

        #Agents are initialized asynchronously due to the use of MCP tools. So we can't initialize the workflow in __init__. We do it lazily here.
        #Reuses the cached workflow for this thread if one already exists (see thread_workflow_store) instead of
        #rebuilding all 9 agents + reconnecting every MCP server on every single message.
        self.workflow = HandoffOrchestrator.thread_workflow_store.get(thread_id)
        was_cached = self.workflow is not None
        if self.workflow is None:
                await self.initialize(checkpoint_storage, thread_id)
        tracker.mark_workflow_ready(was_cached)

        checkpoint = None
        events = None

        # try to retrieve checkpoint for the given thread_id. If None, we start a new conversation.
        checkpoint = await checkpoint_storage.get_latest(workflow_name=self.workflow.name) # type: ignore
        workflow_id = self.workflow.id  # type: ignore

        try:
            if checkpoint is None:
                # Start a new conversation. This is the first user message.
                async for event in self.workflow.run(user_message, stream=True):# type: ignore
                    tracker.track(event)
                    yield event # type: ignore
            else:
                #Resuming an existing conversation.
                async for event in await self._resume_workflow_with_response(checkpoint_storage,
                                                                             checkpoint.checkpoint_id,
                                                                             user_message):
                    tracker.track(event)
                    yield event
        finally:
            tracker.finish()


    async def processToolApprovalResponse(self, thread_id: str, approved:bool, call_id: str, request_id: str, tool_name: str) -> AsyncGenerator[WorkflowEvent,None]:
        """Process a tool approval response from the user.

        Args:
            thread_id (str): The thread ID associated with the workflow.
            approved (bool): Whether the user approved the tool execution.

        """
        tracker = TurnTracker(thread_id, "approval_response")
        tracker.approval_tool = tool_name
        tracker.seed_call(call_id, tool_name)
        checkpoint_storage = await self._get_or_create_checkpoint_store(thread_id)
        tracker.mark_checkpoint_ready()

        self.workflow = HandoffOrchestrator.thread_workflow_store.get(thread_id)
        was_cached = self.workflow is not None
        if self.workflow is None:
               await self.initialize(checkpoint_storage, thread_id)
        tracker.mark_workflow_ready(was_cached)


        checkpoint = await checkpoint_storage.get_latest(workflow_name=self.workflow.name) # type: ignore
        if checkpoint is None:
            raise AgentFrameworkException(f"No checkpoint found for thread_id: {thread_id} when trying to process tool approval response")

        events = self.workflow.run(checkpoint_id=checkpoint.checkpoint_id, #type: ignore
                                   checkpoint_storage=checkpoint_storage, stream=True) #type: ignore

        try:
            responses: dict[str, object] = {}
            #restart the workflow to get the reference to FunctionApprovalRequestEvent
            consumed_events = [event async for event in events]
            for event in consumed_events:
                tracker.track(event)
                yield event
                if event.type == "request_info":
                    if isinstance(event.data, Content) and event.data.type == "function_approval_request":
                            responses[event.request_id] = event.data.to_function_approval_response(approved=approved)
                            async for event in self.workflow.run(responses=responses, #type: ignore
                                                                 checkpoint_id=checkpoint.checkpoint_id,
                                                                 checkpoint_storage=checkpoint_storage, stream=True) : #type: ignore
                                tracker.track(event)
                                yield event
        finally:
            tracker.finish()
