from typing import Any, AsyncGenerator
from collections.abc import AsyncIterable
from agent_framework import AgentResponseUpdate, Agent,InMemoryCheckpointStorage,WorkflowCheckpoint, WorkflowEvent
from agent_framework.orchestrations import HandoffBuilder,HandoffAgentUserRequest
from agent_framework.exceptions import AgentFrameworkException
from agent_framework.openai import OpenAIChatCompletionClient
from app.agents.azure_chat.simple.account_agent import AccountAgent
from app.agents.azure_chat.simple.transaction_agent import TransactionHistoryAgent
from app.agents.azure_chat.simple.payment_agent import PaymentAgent
from uuid import uuid4
import logging

logger = logging.getLogger(__name__)

class HandoffOrchestrator:
    
    triage_instructions = """
      You are a banking customer support agent triaging customer requests about their banking account, movements, payments.
      You have to evaluate the whole conversation with the customer and handoff to AccountAgent, TransactionHistoryAgent, PaymentAgent. 
      When delegation is required, call the matching handoff too based on triage rules.
      
      
      # Triage rules
      - If the user request is related to bank account information like account balance, payment methods, cards and beneficiaries book you must call handoff_to_AccountAgent.
      - If the user request is related to banking movements and payments history, you must call handoff_to_TransactionHistoryAgent.
      - If the user request is related to initiate a payment request, upload a bill or invoice image for payment or manage an on-going payment process, you must call handoff_to_PaymentAgent.
      - If the user request is not related to account, transactions or payments you must respond to the user that you are not able to help with the request.

      
    """

    """ A simple in-memory store [workflow_id/thread_id, WorkflowCheckpoint] to keep track of threads per user/session.
     Thread_id and workflow_id are synonymous in this context. We are keeping the thread_id concept and assign it the workflow_id value generated by the agent framework.
    In production, this should be replaced with a persistent store like a database or distributed cache.
    """
    thread_checkpoint_store: dict[str, WorkflowCheckpoint] = {}
    checkpoint_storage = InMemoryCheckpointStorage()

    def __init__(self, 
                 azure_chat_client: OpenAIChatCompletionClient,
                 account_agent: AccountAgent,
                 transaction_agent: TransactionHistoryAgent,
                 payment_agent: PaymentAgent
                                ):
      self.azure_chat_client = azure_chat_client
      self.account_agent = account_agent
      self.transaction_agent = transaction_agent
      self.payment_agent = payment_agent
      self.workflow = None  # Will be initialized in async method

    async def initialize(self):
      """Initialize the workflow with async operations"""
      triage_agent = Agent(
            client=self.azure_chat_client,
            instructions=HandoffOrchestrator.triage_instructions,
            name="triage_agent"
        )
      
      self.workflow = (
        HandoffBuilder(
            name="banking_assistant_handoff",
            participants=[triage_agent, 
                          await self.account_agent.build_af_agent(),
                          await self.transaction_agent.build_af_agent(),
                          await self.payment_agent.build_af_agent()],
            termination_condition=lambda conv: sum(1 for msg in conv if msg.role == "user") >= 20,
            checkpoint_storage=HandoffOrchestrator.checkpoint_storage,
        )
        .with_start_agent(triage_agent)
        .build()
    )


    async def _handle_events(self, events: AsyncIterable[WorkflowEvent]) -> AsyncGenerator[str, None]:
     
        async for event in events:
            
            if event.type == "output":
                if  event.executor_id != "triage_agent" \
                    and event.data is not None and isinstance(event.data, AgentResponseUpdate) \
                    and event.data.contents \
                    and isinstance(event.data.contents, list) \
                    and all( item.type == "text" for item in event.data.contents):
                    #In our case we just return text
                    yield event.data.contents[0].text #type: ignore
            
    
    async def _resume_workflow_with_response(self, checkpoint_id: str, user_message: str) -> AsyncIterable[WorkflowEvent]:
        """Resume a workflow from a checkpoint with a response to a RequestInfoEvent.

        Args:
            checkpoint (WorkflowCheckpoint): The checkpoint to resume from.
            response (dict[str, str]): The response mapping request IDs to user inputs.

        Yields:
            AsyncIterable[WorkflowEvent]: The events generated by resuming the workflow.
        """
        events = self.workflow.run(checkpoint_id=checkpoint_id, checkpoint_storage=self.checkpoint_storage, stream=True) #type: ignore
        
        responses: dict[str, object] = {}
        
        #We need to collect all workflow events otherwise we get concurrent workflow execution error when trying to resume.
        consumed_events = [event async for event in events]
        for event in consumed_events:
            if event.type == "request_info":
                if isinstance(event.data, HandoffAgentUserRequest):
                        responses[event.request_id] = HandoffAgentUserRequest.create_response(user_message)
                        return self.workflow.run(responses=responses, checkpoint_id=checkpoint_id, #type: ignore
                                                 checkpoint_storage=self.checkpoint_storage, 
                                                 stream=True) #type: ignore
                else:
                    raise AgentFrameworkException(f"RequestInfoEvent [{event.request_id}] found in the checkpoint [{checkpoint_id}] that is not a HandoffAgentUserRequest.")
        #if we reach here, something went wrong. For this use case HandoffOrchestrator expected to always trigger a RequestInfoEvent.
        raise AgentFrameworkException(f"No RequestInfoEvent found in the checkpoint [{checkpoint_id}]")
            
    
    async def processMessageStream(self, user_message: str , thread_id : str | None) -> AsyncGenerator[tuple[str, bool, str | None], None]:
      """Process a chat message and stream the response.

      Yields:
          tuple[str, bool, str | None]: (content_chunk, is_final, thread_id)
              - content_chunk: The text chunk to send
              - is_final: Whether this is the final chunk
              - thread_id: The thread ID (only set on final chunk)
      """
      
      #Agents are initialized asynchronously due to the use of MCP tools. So we can't initialize the workflow in __init__. We do it lazily here.
      if self.workflow is None:
            await self.initialize()
      try:
         
         checkpoint = None
         events = None
        
         if thread_id is None:
             # Start a new conversation. This is the first user message.

             events = self.workflow.run(user_message, stream=True) # type: ignore
             async for chunk in self._handle_events(events):
                 #it's not final and does not have thread id yet
                 yield (chunk, False,self.workflow.id) # type: ignore
             thread_id = self.workflow.id  # type: ignore
         else:
            #Resuming an existing conversation.

            # Retrieve checkpoint for the given thread_id
            checkpoint = HandoffOrchestrator.thread_checkpoint_store.get(thread_id, None)

            if checkpoint is None:
                raise AgentFrameworkException(f"No checkpoint found for thread_id: {thread_id}")
                
            events = await self._resume_workflow_with_response(checkpoint.checkpoint_id, user_message)  
            
            async for chunk in self._handle_events(events):
                # it's not final and does not have thread id yet
                yield (chunk, False, None)

         #Saving the last checkpoint for the conversation thread
         last_checkpoint = await self.checkpoint_storage.get_latest(workflow_name=self.workflow.name) # type: ignore
         if last_checkpoint is None:
            raise AgentFrameworkException(f"No checkpoint found after completing the first conversation for thread_id: {thread_id}")
         #saving the last checkpoint for the conversation thread using workflow_id as thread_id
         HandoffOrchestrator.thread_checkpoint_store[thread_id] = last_checkpoint # type: ignore
         yield ("", True, thread_id) # type: ignore

      
      except Exception as e:
          logger.error(f"Error in processMessageStream: {str(e)}", exc_info=True)
          # Yield error message as content
          error_message = f"I apologize, but I encountered an error while processing your request: {str(e)}"
          yield (error_message, True, thread_id) 



